 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace C2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID P2PChat = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID ReadyPacket = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID SettingEnemyInfo = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID StartPacket = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID LeaveRoom = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID SyncPacket = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID DamagedFromEnemy = (Nettention.Proud.RmiID)2000+7;
			public const Nettention.Proud.RmiID UseSkill = (Nettention.Proud.RmiID)2000+8;
			public const Nettention.Proud.RmiID MatchEnd = (Nettention.Proud.RmiID)2000+9;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			P2PChat,
			ReadyPacket,
			SettingEnemyInfo,
			StartPacket,
			LeaveRoom,
			SyncPacket,
			DamagedFromEnemy,
			UseSkill,
			MatchEnd,
		};
	}
}

				 
