 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace C2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID P2PChat = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID DamagedFromEnemy = (Nettention.Proud.RmiID)2000+2;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			P2PChat,
			DamagedFromEnemy,
		};
	}
}

				 
