 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace C2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID Chat = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID Login = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID RequestMakeRaidRoom = (Nettention.Proud.RmiID)3000+3;
			public const Nettention.Proud.RmiID RequestGetRaidRoomInfo = (Nettention.Proud.RmiID)3000+4;
			public const Nettention.Proud.RmiID RequestJoinRaidRoom = (Nettention.Proud.RmiID)3000+5;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			Chat,
			Login,
			RequestMakeRaidRoom,
			RequestGetRaidRoomInfo,
			RequestJoinRaidRoom,
		};
	}
}

				 
