 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace ChatS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ShowChat = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID UserList_Add = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID UserList_Remove = (Nettention.Proud.RmiID)2000+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ShowChat,
			UserList_Add,
			UserList_Remove,
		};
	}
}

				 
