
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "C2C_common.h"
namespace C2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_P2PChat,
               
		Rmi_ReadyPacket,
               
		Rmi_SettingEnemyInfo,
               
		Rmi_StartPacket,
               
		Rmi_LeaveRoom,
               
		Rmi_SyncPacket,
               
		Rmi_DamagedFromEnemy,
               
		Rmi_UseSkill,
               
		Rmi_MatchEnd,
	};

	int g_RmiIDListCount = 9;

}


