
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "C2S_common.h"
namespace C2S {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Chat,
               
		Rmi_Login,
               
		Rmi_RequestMakeRaidRoom,
               
		Rmi_RequestGetRaidRoomInfo,
               
		Rmi_RequestJoinRaidRoom,
               
		Rmi_RequestMakePVPRoom,
               
		Rmi_RequestGetPVPRoomInfo,
               
		Rmi_RequestJoinPVPRoom,
               
		Rmi_RequestLeavePVPRoom,
               
		Rmi_RequestMakeAccount,
               
		Rmi_RequestLoginAccount,
               
		Rmi_RequestInventoryData,
               
		Rmi_RequestSkillData,
               
		Rmi_RequestEquipData,
               
		Rmi_RequestChangeEquipWeapon,
               
		Rmi_RequestBattleInfo,
               
		Rmi_RequestBattleEnd,
               
		Rmi_AddItemToInventory,
               
		Rmi_AddGold,
               
		Rmi_UseItemFromInventory,
               
		Rmi_UseGold,
               
		Rmi_SellAllItem,
               
		Rmi_SendEquipInfo,
               
		Rmi_SendPassiveEquipInfo,
	};

	int g_RmiIDListCount = 24;

}


