



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "C2S_common.h"

namespace C2S {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & a, const int & b, const float & c) PN_SEALED; 
	virtual bool Chat ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & a, const int & b, const float & c)   PN_SEALED;  
	virtual bool Login ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & id, const Proud::String & password) PN_SEALED; 
	virtual bool Login ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & id, const Proud::String & password)   PN_SEALED;  
	virtual bool RequestMakeRaidRoom ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::HostID & HostId) PN_SEALED; 
	virtual bool RequestMakeRaidRoom ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::HostID & HostId)   PN_SEALED;  
	virtual bool RequestGetRaidRoomInfo ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext ) PN_SEALED; 
	virtual bool RequestGetRaidRoomInfo ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext)   PN_SEALED;  
	virtual bool RequestJoinRaidRoom ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::HostID & HostId, const int & GroupId) PN_SEALED; 
	virtual bool RequestJoinRaidRoom ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::HostID & HostId, const int & GroupId)   PN_SEALED;  
	virtual bool RequestMakePVPRoom ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::HostID & HostId, const Proud::String & CName, const Proud::String & RoomName) PN_SEALED; 
	virtual bool RequestMakePVPRoom ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::HostID & HostId, const Proud::String & CName, const Proud::String & RoomName)   PN_SEALED;  
	virtual bool RequestGetPVPRoomInfo ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext ) PN_SEALED; 
	virtual bool RequestGetPVPRoomInfo ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext)   PN_SEALED;  
	virtual bool RequestJoinPVPRoom ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::HostID & HostId, const int & RoomId, const int & GroupId) PN_SEALED; 
	virtual bool RequestJoinPVPRoom ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::HostID & HostId, const int & RoomId, const int & GroupId)   PN_SEALED;  
	virtual bool RequestLeavePVPRoom ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::HostID & HostId, const Proud::HostID & GroupId) PN_SEALED; 
	virtual bool RequestLeavePVPRoom ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::HostID & HostId, const Proud::HostID & GroupId)   PN_SEALED;  
	virtual bool RequestMakeAccount ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & id, const Proud::String & password, const Proud::String & CName) PN_SEALED; 
	virtual bool RequestMakeAccount ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & id, const Proud::String & password, const Proud::String & CName)   PN_SEALED;  
	virtual bool RequestLoginAccount ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & id, const Proud::String & password) PN_SEALED; 
	virtual bool RequestLoginAccount ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & id, const Proud::String & password)   PN_SEALED;  
	virtual bool RequestInventoryData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName) PN_SEALED; 
	virtual bool RequestInventoryData ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName)   PN_SEALED;  
	virtual bool RequestSkillData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName) PN_SEALED; 
	virtual bool RequestSkillData ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName)   PN_SEALED;  
	virtual bool RequestEquipData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName) PN_SEALED; 
	virtual bool RequestEquipData ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName)   PN_SEALED;  
	virtual bool RequestChangeEquipWeapon ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & weaponIdx) PN_SEALED; 
	virtual bool RequestChangeEquipWeapon ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & weaponIdx)   PN_SEALED;  
	virtual bool RequestBattleInfo ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName) PN_SEALED; 
	virtual bool RequestBattleInfo ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName)   PN_SEALED;  
	virtual bool RequestBattleEnd ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const Proud::CFastArray<items> & itData, const int & battleType, const Proud::CFastArray<battleinfo> & biData) PN_SEALED; 
	virtual bool RequestBattleEnd ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const Proud::CFastArray<items> & itData, const int & battleType, const Proud::CFastArray<battleinfo> & biData)   PN_SEALED;  
	virtual bool AddItemToInventory ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & inId, const int & itemId, const int & itemCount, const int & stackAble) PN_SEALED; 
	virtual bool AddItemToInventory ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & inId, const int & itemId, const int & itemCount, const int & stackAble)   PN_SEALED;  
	virtual bool AddGold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & gold) PN_SEALED; 
	virtual bool AddGold ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & gold)   PN_SEALED;  
	virtual bool UseItemFromInventory ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & inId, const int & itemId, const int & itemCount, const int & stackAble) PN_SEALED; 
	virtual bool UseItemFromInventory ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & inId, const int & itemId, const int & itemCount, const int & stackAble)   PN_SEALED;  
	virtual bool UseGold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & gold) PN_SEALED; 
	virtual bool UseGold ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & gold)   PN_SEALED;  
	virtual bool SellAllItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & inId, const int & itemId) PN_SEALED; 
	virtual bool SellAllItem ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & inId, const int & itemId)   PN_SEALED;  
	virtual bool SendEquipInfo ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & equipslot1, const int & equipslot2, const int & equipslot3, const int & equipslot4, const int & equipslot5, const int & equipslot6) PN_SEALED; 
	virtual bool SendEquipInfo ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & equipslot1, const int & equipslot2, const int & equipslot3, const int & equipslot4, const int & equipslot5, const int & equipslot6)   PN_SEALED;  
	virtual bool SendPassiveEquipInfo ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & CName, const int & equipslot1, const int & equipslot2, const int & equipslot3, const int & equipslot4) PN_SEALED; 
	virtual bool SendPassiveEquipInfo ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & CName, const int & equipslot1, const int & equipslot2, const int & equipslot3, const int & equipslot4)   PN_SEALED;  
static const PNTCHAR* RmiName_Chat;
static const PNTCHAR* RmiName_Login;
static const PNTCHAR* RmiName_RequestMakeRaidRoom;
static const PNTCHAR* RmiName_RequestGetRaidRoomInfo;
static const PNTCHAR* RmiName_RequestJoinRaidRoom;
static const PNTCHAR* RmiName_RequestMakePVPRoom;
static const PNTCHAR* RmiName_RequestGetPVPRoomInfo;
static const PNTCHAR* RmiName_RequestJoinPVPRoom;
static const PNTCHAR* RmiName_RequestLeavePVPRoom;
static const PNTCHAR* RmiName_RequestMakeAccount;
static const PNTCHAR* RmiName_RequestLoginAccount;
static const PNTCHAR* RmiName_RequestInventoryData;
static const PNTCHAR* RmiName_RequestSkillData;
static const PNTCHAR* RmiName_RequestEquipData;
static const PNTCHAR* RmiName_RequestChangeEquipWeapon;
static const PNTCHAR* RmiName_RequestBattleInfo;
static const PNTCHAR* RmiName_RequestBattleEnd;
static const PNTCHAR* RmiName_AddItemToInventory;
static const PNTCHAR* RmiName_AddGold;
static const PNTCHAR* RmiName_UseItemFromInventory;
static const PNTCHAR* RmiName_UseGold;
static const PNTCHAR* RmiName_SellAllItem;
static const PNTCHAR* RmiName_SendEquipInfo;
static const PNTCHAR* RmiName_SendPassiveEquipInfo;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



