
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "S2C_common.h"
namespace S2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_ShowChat,
               
		Rmi_SystemChat,
               
		Rmi_sendUserInfo,
               
		Rmi_sendInventoryData,
               
		Rmi_sendRaidRoomInfo,
               
		Rmi_sendMakePVPRoomResult,
               
		Rmi_sendPVPRoomInfo,
               
		Rmi_sendRoomHostId,
               
		Rmi_sendPVPRoomJoinResult,
               
		Rmi_sendMakeAccountResult,
               
		Rmi_sendLoginResult,
               
		Rmi_sendSkillData,
               
		Rmi_sendEquipmentData,
               
		Rmi_sendChangeEquipWeaponResult,
               
		Rmi_sendBattleInfoResult,
	};

	int g_RmiIDListCount = 15;

}


